[tool.black]
line-length = 110
target-version = ["py27"]  # Specify Python 2.7 for compatibility
include = '\.py$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''